import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col bg-[#121212]">
          {<Navbar />}
          <div className="container   min-h-screen  mt-24 mx-auto px-12 py-4">
            {children}
          </div>
          {<Footer />}
        </main>
      </body>
    </html>
  );
}
